### ISSUE TITLE
Embed this project to my application

### ISSUE THREAD

**Issue by yanis60** [eclipsesource/papyrus-gefx#15]
Hi,

I want to develop a java program which allow me to draw class diagram like Papyrus, i want to embed this project to my application if possible.

Can you help me please how to embed it?

Thank you

**Comment by CamilleLetavernier** [comment]
Hi,

For now, this project is very early work-in-progress, and only works inside Eclipse. Even later on, it is very unlikely that this would work in a plain-java application, because Papyrus itself needs Eclipse to work.

**Comment by yanis60** [comment]
Hi,

Thanks for the reply, is there any similar library which i can embed it to my application? because i really need an api to draw diagrams uml please can you help me?

**Comment by CamilleLetavernier** [comment]
Hi,

I'm not aware of any current open-source UML modeling tool in Java that is not based on Eclipse (Historically, they have been based on GMF, which can't work outside Eclipse, due to the intensive use of plug-ins and extension points)

You may try Modelio (https://www.modelio.org/), which is also based on Eclipse, but maybe their Editor/Viewer isn't too tightly coupled to the Eclipse infrastructure? I wouldn't bet on that, though.

Sirius/UML Designer (http://www.umldesigner.org/) is also an open source UML Modeler, but it is also based on Eclipse/GMF, so the chances are that it won't work outside Eclipse either.

**Comment by yanis60** [comment]
Hi,

ok thank you for your replies, i appreciate you answers.
